// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/notify.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_SendToUser_FullMethodName         = "/notify.NotifyService/SendToUser"
	NotifyService_SendToUsers_FullMethodName        = "/notify.NotifyService/SendToUsers"
	NotifyService_SendToAll_FullMethodName          = "/notify.NotifyService/SendToAll"
	NotifyService_MarkRead_FullMethodName           = "/notify.NotifyService/MarkRead"
	NotifyService_DeleteNotify_FullMethodName       = "/notify.NotifyService/DeleteNotify"
	NotifyService_ApplyTicket_FullMethodName        = "/notify.NotifyService/ApplyTicket"
	NotifyService_BatchMarkRead_FullMethodName      = "/notify.NotifyService/BatchMarkRead"
	NotifyService_BatchDeleteNotify_FullMethodName  = "/notify.NotifyService/BatchDeleteNotify"
	NotifyService_GetPersonalInbox_FullMethodName   = "/notify.NotifyService/GetPersonalInbox"
	NotifyService_GetTenantInbox_FullMethodName     = "/notify.NotifyService/GetTenantInbox"
	NotifyService_GetUserNotifyStats_FullMethodName = "/notify.NotifyService/GetUserNotifyStats"
	NotifyService_Connect_FullMethodName            = "/notify.NotifyService/Connect"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NotifyService 通知中心核心服务
type NotifyServiceClient interface {
	// SendToUser 一对一发送通知
	SendToUser(ctx context.Context, in *SendToUserReq, opts ...grpc.CallOption) (*SendNotifyRes, error)
	// SendToUsers 一对多发送通知
	SendToUsers(ctx context.Context, in *SendToUsersReq, opts ...grpc.CallOption) (*SendNotifyRes, error)
	// SendToAll 租户全员广播通知
	SendToAll(ctx context.Context, in *SendToAllReq, opts ...grpc.CallOption) (*SendNotifyRes, error)
	// MarkRead 标记通知已读
	MarkRead(ctx context.Context, in *OperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteNotify 删除通知
	DeleteNotify(ctx context.Context, in *OperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ApplyTicket 申请订阅凭证
	ApplyTicket(ctx context.Context, in *ApplyTicketReq, opts ...grpc.CallOption) (*ApplyTicketRes, error)
	// BatchMarkRead 一键标记通知已读
	BatchMarkRead(ctx context.Context, in *BatchOperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BatchDeleteNotify 一键清空通知
	BatchDeleteNotify(ctx context.Context, in *BatchOperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetPersonalInbox 查询个人收件箱分页数据
	GetPersonalInbox(ctx context.Context, in *GetInboxReq, opts ...grpc.CallOption) (*GetInboxRes, error)
	// GetTenantInbox 查询租户收件箱分页数据
	GetTenantInbox(ctx context.Context, in *GetInboxReq, opts ...grpc.CallOption) (*GetInboxRes, error)
	// GetUserNotifyStats 获取用户个人和租户通知统计（总数与未读数）
	GetUserNotifyStats(ctx context.Context, in *GetUserNotifyStatsReq, opts ...grpc.CallOption) (*GetUserNotifyStatsRes, error)
	// Connect 测试远端调用连通性
	Connect(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConnectRes, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) SendToUser(ctx context.Context, in *SendToUserReq, opts ...grpc.CallOption) (*SendNotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotifyRes)
	err := c.cc.Invoke(ctx, NotifyService_SendToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) SendToUsers(ctx context.Context, in *SendToUsersReq, opts ...grpc.CallOption) (*SendNotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotifyRes)
	err := c.cc.Invoke(ctx, NotifyService_SendToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) SendToAll(ctx context.Context, in *SendToAllReq, opts ...grpc.CallOption) (*SendNotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotifyRes)
	err := c.cc.Invoke(ctx, NotifyService_SendToAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) MarkRead(ctx context.Context, in *OperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotifyService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) DeleteNotify(ctx context.Context, in *OperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotifyService_DeleteNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) ApplyTicket(ctx context.Context, in *ApplyTicketReq, opts ...grpc.CallOption) (*ApplyTicketRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyTicketRes)
	err := c.cc.Invoke(ctx, NotifyService_ApplyTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) BatchMarkRead(ctx context.Context, in *BatchOperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotifyService_BatchMarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) BatchDeleteNotify(ctx context.Context, in *BatchOperateNotifyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotifyService_BatchDeleteNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetPersonalInbox(ctx context.Context, in *GetInboxReq, opts ...grpc.CallOption) (*GetInboxRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInboxRes)
	err := c.cc.Invoke(ctx, NotifyService_GetPersonalInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetTenantInbox(ctx context.Context, in *GetInboxReq, opts ...grpc.CallOption) (*GetInboxRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInboxRes)
	err := c.cc.Invoke(ctx, NotifyService_GetTenantInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetUserNotifyStats(ctx context.Context, in *GetUserNotifyStatsReq, opts ...grpc.CallOption) (*GetUserNotifyStatsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotifyStatsRes)
	err := c.cc.Invoke(ctx, NotifyService_GetUserNotifyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) Connect(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConnectRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectRes)
	err := c.cc.Invoke(ctx, NotifyService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
//
// NotifyService 通知中心核心服务
type NotifyServiceServer interface {
	// SendToUser 一对一发送通知
	SendToUser(context.Context, *SendToUserReq) (*SendNotifyRes, error)
	// SendToUsers 一对多发送通知
	SendToUsers(context.Context, *SendToUsersReq) (*SendNotifyRes, error)
	// SendToAll 租户全员广播通知
	SendToAll(context.Context, *SendToAllReq) (*SendNotifyRes, error)
	// MarkRead 标记通知已读
	MarkRead(context.Context, *OperateNotifyStatusReq) (*emptypb.Empty, error)
	// DeleteNotify 删除通知
	DeleteNotify(context.Context, *OperateNotifyStatusReq) (*emptypb.Empty, error)
	// ApplyTicket 申请订阅凭证
	ApplyTicket(context.Context, *ApplyTicketReq) (*ApplyTicketRes, error)
	// BatchMarkRead 一键标记通知已读
	BatchMarkRead(context.Context, *BatchOperateNotifyStatusReq) (*emptypb.Empty, error)
	// BatchDeleteNotify 一键清空通知
	BatchDeleteNotify(context.Context, *BatchOperateNotifyStatusReq) (*emptypb.Empty, error)
	// GetPersonalInbox 查询个人收件箱分页数据
	GetPersonalInbox(context.Context, *GetInboxReq) (*GetInboxRes, error)
	// GetTenantInbox 查询租户收件箱分页数据
	GetTenantInbox(context.Context, *GetInboxReq) (*GetInboxRes, error)
	// GetUserNotifyStats 获取用户个人和租户通知统计（总数与未读数）
	GetUserNotifyStats(context.Context, *GetUserNotifyStatsReq) (*GetUserNotifyStatsRes, error)
	// Connect 测试远端调用连通性
	Connect(context.Context, *emptypb.Empty) (*ConnectRes, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) SendToUser(context.Context, *SendToUserReq) (*SendNotifyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToUser not implemented")
}
func (UnimplementedNotifyServiceServer) SendToUsers(context.Context, *SendToUsersReq) (*SendNotifyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToUsers not implemented")
}
func (UnimplementedNotifyServiceServer) SendToAll(context.Context, *SendToAllReq) (*SendNotifyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToAll not implemented")
}
func (UnimplementedNotifyServiceServer) MarkRead(context.Context, *OperateNotifyStatusReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedNotifyServiceServer) DeleteNotify(context.Context, *OperateNotifyStatusReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNotify not implemented")
}
func (UnimplementedNotifyServiceServer) ApplyTicket(context.Context, *ApplyTicketReq) (*ApplyTicketRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTicket not implemented")
}
func (UnimplementedNotifyServiceServer) BatchMarkRead(context.Context, *BatchOperateNotifyStatusReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchMarkRead not implemented")
}
func (UnimplementedNotifyServiceServer) BatchDeleteNotify(context.Context, *BatchOperateNotifyStatusReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteNotify not implemented")
}
func (UnimplementedNotifyServiceServer) GetPersonalInbox(context.Context, *GetInboxReq) (*GetInboxRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonalInbox not implemented")
}
func (UnimplementedNotifyServiceServer) GetTenantInbox(context.Context, *GetInboxReq) (*GetInboxRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantInbox not implemented")
}
func (UnimplementedNotifyServiceServer) GetUserNotifyStats(context.Context, *GetUserNotifyStatsReq) (*GetUserNotifyStatsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotifyStats not implemented")
}
func (UnimplementedNotifyServiceServer) Connect(context.Context, *emptypb.Empty) (*ConnectRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_SendToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).SendToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_SendToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).SendToUser(ctx, req.(*SendToUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_SendToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).SendToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_SendToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).SendToUsers(ctx, req.(*SendToUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_SendToAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).SendToAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_SendToAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).SendToAll(ctx, req.(*SendToAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateNotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).MarkRead(ctx, req.(*OperateNotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_DeleteNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateNotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).DeleteNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_DeleteNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).DeleteNotify(ctx, req.(*OperateNotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_ApplyTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).ApplyTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_ApplyTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).ApplyTicket(ctx, req.(*ApplyTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_BatchMarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchOperateNotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).BatchMarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_BatchMarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).BatchMarkRead(ctx, req.(*BatchOperateNotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_BatchDeleteNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchOperateNotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).BatchDeleteNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_BatchDeleteNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).BatchDeleteNotify(ctx, req.(*BatchOperateNotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetPersonalInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetPersonalInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetPersonalInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetPersonalInbox(ctx, req.(*GetInboxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetTenantInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetTenantInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetTenantInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetTenantInbox(ctx, req.(*GetInboxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetUserNotifyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotifyStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetUserNotifyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetUserNotifyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetUserNotifyStats(ctx, req.(*GetUserNotifyStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).Connect(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToUser",
			Handler:    _NotifyService_SendToUser_Handler,
		},
		{
			MethodName: "SendToUsers",
			Handler:    _NotifyService_SendToUsers_Handler,
		},
		{
			MethodName: "SendToAll",
			Handler:    _NotifyService_SendToAll_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _NotifyService_MarkRead_Handler,
		},
		{
			MethodName: "DeleteNotify",
			Handler:    _NotifyService_DeleteNotify_Handler,
		},
		{
			MethodName: "ApplyTicket",
			Handler:    _NotifyService_ApplyTicket_Handler,
		},
		{
			MethodName: "BatchMarkRead",
			Handler:    _NotifyService_BatchMarkRead_Handler,
		},
		{
			MethodName: "BatchDeleteNotify",
			Handler:    _NotifyService_BatchDeleteNotify_Handler,
		},
		{
			MethodName: "GetPersonalInbox",
			Handler:    _NotifyService_GetPersonalInbox_Handler,
		},
		{
			MethodName: "GetTenantInbox",
			Handler:    _NotifyService_GetTenantInbox_Handler,
		},
		{
			MethodName: "GetUserNotifyStats",
			Handler:    _NotifyService_GetUserNotifyStats_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _NotifyService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/notify.proto",
}
