// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/notify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送者类型
type SenderType int32

const (
	SenderType_USER   SenderType = 0
	SenderType_TENANT SenderType = 1
)

// Enum value maps for SenderType.
var (
	SenderType_name = map[int32]string{
		0: "USER",
		1: "TENANT",
	}
	SenderType_value = map[string]int32{
		"USER":   0,
		"TENANT": 1,
	}
)

func (x SenderType) Enum() *SenderType {
	p := new(SenderType)
	*p = x
	return p
}

func (x SenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notify_proto_enumTypes[0].Descriptor()
}

func (SenderType) Type() protoreflect.EnumType {
	return &file_api_proto_notify_proto_enumTypes[0]
}

func (x SenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderType.Descriptor instead.
func (SenderType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{0}
}

// 发送通知响应
type SendNotifyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyId      string                 `protobuf:"bytes,1,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	ExpireTime    *string                `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3,oneof" json:"expire_time,omitempty"` // 为空代表永久不过期，ISO格式
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotifyRes) Reset() {
	*x = SendNotifyRes{}
	mi := &file_api_proto_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotifyRes) ProtoMessage() {}

func (x *SendNotifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotifyRes.ProtoReflect.Descriptor instead.
func (*SendNotifyRes) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotifyRes) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *SendNotifyRes) GetExpireTime() string {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return ""
}

func (x *SendNotifyRes) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// 一对一发送请求
type SendToUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                     // 标题
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                 // 内容
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                     // 目标用户 ID
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                               // 发送者 ID
	SenderType    SenderType             `protobuf:"varint,5,opt,name=sender_type,json=senderType,proto3,enum=notify.SenderType" json:"sender_type,omitempty"` // 发送者类型: 0-用户 1-租户
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                            // 事件类型 (透传字段)
	TtlSeconds    *int64                 `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`                  // 消息过期时间(秒)，可选
	TenantId      string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                               // 消息所属租户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserReq) Reset() {
	*x = SendToUserReq{}
	mi := &file_api_proto_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserReq) ProtoMessage() {}

func (x *SendToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserReq.ProtoReflect.Descriptor instead.
func (*SendToUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{1}
}

func (x *SendToUserReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendToUserReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendToUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendToUserReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendToUserReq) GetSenderType() SenderType {
	if x != nil {
		return x.SenderType
	}
	return SenderType_USER
}

func (x *SendToUserReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendToUserReq) GetTtlSeconds() int64 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *SendToUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 一对多发送请求
type SendToUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 目标用户 ID 列表
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderType    SenderType             `protobuf:"varint,5,opt,name=sender_type,json=senderType,proto3,enum=notify.SenderType" json:"sender_type,omitempty"` // 发送者类型: 0-用户 1-租户
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TtlSeconds    *int64                 `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"` // 消息过期时间(秒)，可选
	TenantId      string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`              // 消息所属租户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersReq) Reset() {
	*x = SendToUsersReq{}
	mi := &file_api_proto_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersReq) ProtoMessage() {}

func (x *SendToUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersReq.ProtoReflect.Descriptor instead.
func (*SendToUsersReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{2}
}

func (x *SendToUsersReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendToUsersReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendToUsersReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendToUsersReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendToUsersReq) GetSenderType() SenderType {
	if x != nil {
		return x.SenderType
	}
	return SenderType_USER
}

func (x *SendToUsersReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendToUsersReq) GetTtlSeconds() int64 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *SendToUsersReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 租户全员发送请求
type SendToAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 目标租户 ID
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderType    SenderType             `protobuf:"varint,5,opt,name=sender_type,json=senderType,proto3,enum=notify.SenderType" json:"sender_type,omitempty"` // 发送者类型: 0-用户 1-租户
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TtlSeconds    *int64                 `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"` // 消息过期时间(秒)，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToAllReq) Reset() {
	*x = SendToAllReq{}
	mi := &file_api_proto_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAllReq) ProtoMessage() {}

func (x *SendToAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAllReq.ProtoReflect.Descriptor instead.
func (*SendToAllReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{3}
}

func (x *SendToAllReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendToAllReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendToAllReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SendToAllReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendToAllReq) GetSenderType() SenderType {
	if x != nil {
		return x.SenderType
	}
	return SenderType_USER
}

func (x *SendToAllReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendToAllReq) GetTtlSeconds() int64 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

// 通知状态操作请求（已读/删除）
type OperateNotifyStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyId      string                 `protobuf:"bytes,1,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateNotifyStatusReq) Reset() {
	*x = OperateNotifyStatusReq{}
	mi := &file_api_proto_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateNotifyStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateNotifyStatusReq) ProtoMessage() {}

func (x *OperateNotifyStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateNotifyStatusReq.ProtoReflect.Descriptor instead.
func (*OperateNotifyStatusReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{4}
}

func (x *OperateNotifyStatusReq) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *OperateNotifyStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OperateNotifyStatusReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 凭证申请请求
type ApplyTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`               // 租户标识
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTicketReq) Reset() {
	*x = ApplyTicketReq{}
	mi := &file_api_proto_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTicketReq) ProtoMessage() {}

func (x *ApplyTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTicketReq.ProtoReflect.Descriptor instead.
func (*ApplyTicketReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyTicketReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ApplyTicketReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 凭证申请响应
type ApplyTicketRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	CreateTime    string                 `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTicketRes) Reset() {
	*x = ApplyTicketRes{}
	mi := &file_api_proto_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTicketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTicketRes) ProtoMessage() {}

func (x *ApplyTicketRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTicketRes.ProtoReflect.Descriptor instead.
func (*ApplyTicketRes) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyTicketRes) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *ApplyTicketRes) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *ApplyTicketRes) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 批量状态操作请求
type BatchOperateNotifyStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 0-用户 1-租户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperateNotifyStatusReq) Reset() {
	*x = BatchOperateNotifyStatusReq{}
	mi := &file_api_proto_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperateNotifyStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperateNotifyStatusReq) ProtoMessage() {}

func (x *BatchOperateNotifyStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperateNotifyStatusReq.ProtoReflect.Descriptor instead.
func (*BatchOperateNotifyStatusReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{7}
}

func (x *BatchOperateNotifyStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchOperateNotifyStatusReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchOperateNotifyStatusReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 收件箱分页查询请求
type GetInboxReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageIndex     int32                  `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboxReq) Reset() {
	*x = GetInboxReq{}
	mi := &file_api_proto_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboxReq) ProtoMessage() {}

func (x *GetInboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboxReq.ProtoReflect.Descriptor instead.
func (*GetInboxReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{8}
}

func (x *GetInboxReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetInboxReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInboxReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetInboxReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 收件箱通知项
type InboxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyId      string                 `protobuf:"bytes,1,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SenderType    int32                  `protobuf:"varint,4,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	SenderId      string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // 0-未读 1-已读
	ExpireAt      *string                `protobuf:"bytes,8,opt,name=expire_at,json=expireAt,proto3,oneof" json:"expire_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxItem) Reset() {
	*x = InboxItem{}
	mi := &file_api_proto_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxItem) ProtoMessage() {}

func (x *InboxItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxItem.ProtoReflect.Descriptor instead.
func (*InboxItem) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{9}
}

func (x *InboxItem) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *InboxItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InboxItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InboxItem) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *InboxItem) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *InboxItem) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *InboxItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InboxItem) GetExpireAt() string {
	if x != nil && x.ExpireAt != nil {
		return *x.ExpireAt
	}
	return ""
}

func (x *InboxItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 收件箱分页查询响应
type GetInboxRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     int32                  `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Unread        int64                  `protobuf:"varint,4,opt,name=unread,proto3" json:"unread,omitempty"`
	List          []*InboxItem           `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboxRes) Reset() {
	*x = GetInboxRes{}
	mi := &file_api_proto_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboxRes) ProtoMessage() {}

func (x *GetInboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboxRes.ProtoReflect.Descriptor instead.
func (*GetInboxRes) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{10}
}

func (x *GetInboxRes) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetInboxRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetInboxRes) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetInboxRes) GetUnread() int64 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *GetInboxRes) GetList() []*InboxItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 用户通知统计请求
type GetUserNotifyStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNotifyStatsReq) Reset() {
	*x = GetUserNotifyStatsReq{}
	mi := &file_api_proto_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNotifyStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNotifyStatsReq) ProtoMessage() {}

func (x *GetUserNotifyStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNotifyStatsReq.ProtoReflect.Descriptor instead.
func (*GetUserNotifyStatsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserNotifyStatsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserNotifyStatsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 通知统计项（总数与未读数）
type NotifyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Unread        int64                  `protobuf:"varint,2,opt,name=unread,proto3" json:"unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyStats) Reset() {
	*x = NotifyStats{}
	mi := &file_api_proto_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyStats) ProtoMessage() {}

func (x *NotifyStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyStats.ProtoReflect.Descriptor instead.
func (*NotifyStats) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NotifyStats) GetUnread() int64 {
	if x != nil {
		return x.Unread
	}
	return 0
}

// 用户通知统计响应
type GetUserNotifyStatsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personal      *NotifyStats           `protobuf:"bytes,1,opt,name=personal,proto3" json:"personal,omitempty"` // 个人通知统计
	Tenant        *NotifyStats           `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`     // 租户通知统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNotifyStatsRes) Reset() {
	*x = GetUserNotifyStatsRes{}
	mi := &file_api_proto_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNotifyStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNotifyStatsRes) ProtoMessage() {}

func (x *GetUserNotifyStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNotifyStatsRes.ProtoReflect.Descriptor instead.
func (*GetUserNotifyStatsRes) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserNotifyStatsRes) GetPersonal() *NotifyStats {
	if x != nil {
		return x.Personal
	}
	return nil
}

func (x *GetUserNotifyStatsRes) GetTenant() *NotifyStats {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// 连通性测试响应
type ConnectRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRes) Reset() {
	*x = ConnectRes{}
	mi := &file_api_proto_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRes) ProtoMessage() {}

func (x *ConnectRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRes.ProtoReflect.Descriptor instead.
func (*ConnectRes) Descriptor() ([]byte, []int) {
	return file_api_proto_notify_proto_rawDescGZIP(), []int{14}
}

func (x *ConnectRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_notify_proto protoreflect.FileDescriptor

const file_api_proto_notify_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/notify.proto\x12\x06notify\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x01\n" +
	"\rSendNotifyRes\x12\x1b\n" +
	"\tnotify_id\x18\x01 \x01(\tR\bnotifyId\x12$\n" +
	"\vexpire_time\x18\x02 \x01(\tH\x00R\n" +
	"expireTime\x88\x01\x01\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSecondsB\x0e\n" +
	"\f_expire_time\"\x9c\x02\n" +
	"\rSendToUserReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x123\n" +
	"\vsender_type\x18\x05 \x01(\x0e2\x12.notify.SenderTypeR\n" +
	"senderType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12$\n" +
	"\vttl_seconds\x18\a \x01(\x03H\x00R\n" +
	"ttlSeconds\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantIdB\x0e\n" +
	"\f_ttl_seconds\"\x9f\x02\n" +
	"\x0eSendToUsersReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x123\n" +
	"\vsender_type\x18\x05 \x01(\x0e2\x12.notify.SenderTypeR\n" +
	"senderType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12$\n" +
	"\vttl_seconds\x18\a \x01(\x03H\x00R\n" +
	"ttlSeconds\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantIdB\x0e\n" +
	"\f_ttl_seconds\"\x82\x02\n" +
	"\fSendToAllReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x123\n" +
	"\vsender_type\x18\x05 \x01(\x0e2\x12.notify.SenderTypeR\n" +
	"senderType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12$\n" +
	"\vttl_seconds\x18\a \x01(\x03H\x00R\n" +
	"ttlSeconds\x88\x01\x01B\x0e\n" +
	"\f_ttl_seconds\"k\n" +
	"\x16OperateNotifyStatusReq\x12\x1b\n" +
	"\tnotify_id\x18\x01 \x01(\tR\bnotifyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"A\n" +
	"\x0eApplyTicketReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"j\n" +
	"\x0eApplyTicketRes\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\tR\n" +
	"expireTime\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\tR\n" +
	"createTime\"g\n" +
	"\x1bBatchOperateNotifyStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"\x7f\n" +
	"\vGetInboxReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"page_index\x18\x03 \x01(\x05R\tpageIndex\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x9c\x02\n" +
	"\tInboxItem\x12\x1b\n" +
	"\tnotify_id\x18\x01 \x01(\tR\bnotifyId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vsender_type\x18\x04 \x01(\x05R\n" +
	"senderType\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12 \n" +
	"\texpire_at\x18\b \x01(\tH\x00R\bexpireAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\f\n" +
	"\n" +
	"_expire_at\"\x9e\x01\n" +
	"\vGetInboxRes\x12\x1d\n" +
	"\n" +
	"page_index\x18\x01 \x01(\x05R\tpageIndex\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06unread\x18\x04 \x01(\x03R\x06unread\x12%\n" +
	"\x04list\x18\x05 \x03(\v2\x11.notify.InboxItemR\x04list\"M\n" +
	"\x15GetUserNotifyStatsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\";\n" +
	"\vNotifyStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06unread\x18\x02 \x01(\x03R\x06unread\"u\n" +
	"\x15GetUserNotifyStatsRes\x12/\n" +
	"\bpersonal\x18\x01 \x01(\v2\x13.notify.NotifyStatsR\bpersonal\x12+\n" +
	"\x06tenant\x18\x02 \x01(\v2\x13.notify.NotifyStatsR\x06tenant\"&\n" +
	"\n" +
	"ConnectRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\"\n" +
	"\n" +
	"SenderType\x12\b\n" +
	"\x04USER\x10\x00\x12\n" +
	"\n" +
	"\x06TENANT\x10\x012\xb3\x06\n" +
	"\rNotifyService\x12:\n" +
	"\n" +
	"SendToUser\x12\x15.notify.SendToUserReq\x1a\x15.notify.SendNotifyRes\x12<\n" +
	"\vSendToUsers\x12\x16.notify.SendToUsersReq\x1a\x15.notify.SendNotifyRes\x128\n" +
	"\tSendToAll\x12\x14.notify.SendToAllReq\x1a\x15.notify.SendNotifyRes\x12B\n" +
	"\bMarkRead\x12\x1e.notify.OperateNotifyStatusReq\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\fDeleteNotify\x12\x1e.notify.OperateNotifyStatusReq\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\vApplyTicket\x12\x16.notify.ApplyTicketReq\x1a\x16.notify.ApplyTicketRes\x12L\n" +
	"\rBatchMarkRead\x12#.notify.BatchOperateNotifyStatusReq\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11BatchDeleteNotify\x12#.notify.BatchOperateNotifyStatusReq\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\x10GetPersonalInbox\x12\x13.notify.GetInboxReq\x1a\x13.notify.GetInboxRes\x12:\n" +
	"\x0eGetTenantInbox\x12\x13.notify.GetInboxReq\x1a\x13.notify.GetInboxRes\x12R\n" +
	"\x12GetUserNotifyStats\x12\x1d.notify.GetUserNotifyStatsReq\x1a\x1d.notify.GetUserNotifyStatsRes\x125\n" +
	"\aConnect\x12\x16.google.protobuf.Empty\x1a\x12.notify.ConnectResB\rZ\v./api/protob\x06proto3"

var (
	file_api_proto_notify_proto_rawDescOnce sync.Once
	file_api_proto_notify_proto_rawDescData []byte
)

func file_api_proto_notify_proto_rawDescGZIP() []byte {
	file_api_proto_notify_proto_rawDescOnce.Do(func() {
		file_api_proto_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notify_proto_rawDesc), len(file_api_proto_notify_proto_rawDesc)))
	})
	return file_api_proto_notify_proto_rawDescData
}

var file_api_proto_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_notify_proto_goTypes = []any{
	(SenderType)(0),                     // 0: notify.SenderType
	(*SendNotifyRes)(nil),               // 1: notify.SendNotifyRes
	(*SendToUserReq)(nil),               // 2: notify.SendToUserReq
	(*SendToUsersReq)(nil),              // 3: notify.SendToUsersReq
	(*SendToAllReq)(nil),                // 4: notify.SendToAllReq
	(*OperateNotifyStatusReq)(nil),      // 5: notify.OperateNotifyStatusReq
	(*ApplyTicketReq)(nil),              // 6: notify.ApplyTicketReq
	(*ApplyTicketRes)(nil),              // 7: notify.ApplyTicketRes
	(*BatchOperateNotifyStatusReq)(nil), // 8: notify.BatchOperateNotifyStatusReq
	(*GetInboxReq)(nil),                 // 9: notify.GetInboxReq
	(*InboxItem)(nil),                   // 10: notify.InboxItem
	(*GetInboxRes)(nil),                 // 11: notify.GetInboxRes
	(*GetUserNotifyStatsReq)(nil),       // 12: notify.GetUserNotifyStatsReq
	(*NotifyStats)(nil),                 // 13: notify.NotifyStats
	(*GetUserNotifyStatsRes)(nil),       // 14: notify.GetUserNotifyStatsRes
	(*ConnectRes)(nil),                  // 15: notify.ConnectRes
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
}
var file_api_proto_notify_proto_depIdxs = []int32{
	0,  // 0: notify.SendToUserReq.sender_type:type_name -> notify.SenderType
	0,  // 1: notify.SendToUsersReq.sender_type:type_name -> notify.SenderType
	0,  // 2: notify.SendToAllReq.sender_type:type_name -> notify.SenderType
	10, // 3: notify.GetInboxRes.list:type_name -> notify.InboxItem
	13, // 4: notify.GetUserNotifyStatsRes.personal:type_name -> notify.NotifyStats
	13, // 5: notify.GetUserNotifyStatsRes.tenant:type_name -> notify.NotifyStats
	2,  // 6: notify.NotifyService.SendToUser:input_type -> notify.SendToUserReq
	3,  // 7: notify.NotifyService.SendToUsers:input_type -> notify.SendToUsersReq
	4,  // 8: notify.NotifyService.SendToAll:input_type -> notify.SendToAllReq
	5,  // 9: notify.NotifyService.MarkRead:input_type -> notify.OperateNotifyStatusReq
	5,  // 10: notify.NotifyService.DeleteNotify:input_type -> notify.OperateNotifyStatusReq
	6,  // 11: notify.NotifyService.ApplyTicket:input_type -> notify.ApplyTicketReq
	8,  // 12: notify.NotifyService.BatchMarkRead:input_type -> notify.BatchOperateNotifyStatusReq
	8,  // 13: notify.NotifyService.BatchDeleteNotify:input_type -> notify.BatchOperateNotifyStatusReq
	9,  // 14: notify.NotifyService.GetPersonalInbox:input_type -> notify.GetInboxReq
	9,  // 15: notify.NotifyService.GetTenantInbox:input_type -> notify.GetInboxReq
	12, // 16: notify.NotifyService.GetUserNotifyStats:input_type -> notify.GetUserNotifyStatsReq
	16, // 17: notify.NotifyService.Connect:input_type -> google.protobuf.Empty
	1,  // 18: notify.NotifyService.SendToUser:output_type -> notify.SendNotifyRes
	1,  // 19: notify.NotifyService.SendToUsers:output_type -> notify.SendNotifyRes
	1,  // 20: notify.NotifyService.SendToAll:output_type -> notify.SendNotifyRes
	16, // 21: notify.NotifyService.MarkRead:output_type -> google.protobuf.Empty
	16, // 22: notify.NotifyService.DeleteNotify:output_type -> google.protobuf.Empty
	7,  // 23: notify.NotifyService.ApplyTicket:output_type -> notify.ApplyTicketRes
	16, // 24: notify.NotifyService.BatchMarkRead:output_type -> google.protobuf.Empty
	16, // 25: notify.NotifyService.BatchDeleteNotify:output_type -> google.protobuf.Empty
	11, // 26: notify.NotifyService.GetPersonalInbox:output_type -> notify.GetInboxRes
	11, // 27: notify.NotifyService.GetTenantInbox:output_type -> notify.GetInboxRes
	14, // 28: notify.NotifyService.GetUserNotifyStats:output_type -> notify.GetUserNotifyStatsRes
	15, // 29: notify.NotifyService.Connect:output_type -> notify.ConnectRes
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_notify_proto_init() }
func file_api_proto_notify_proto_init() {
	if File_api_proto_notify_proto != nil {
		return
	}
	file_api_proto_notify_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_notify_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_notify_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_notify_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_notify_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notify_proto_rawDesc), len(file_api_proto_notify_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notify_proto_goTypes,
		DependencyIndexes: file_api_proto_notify_proto_depIdxs,
		EnumInfos:         file_api_proto_notify_proto_enumTypes,
		MessageInfos:      file_api_proto_notify_proto_msgTypes,
	}.Build()
	File_api_proto_notify_proto = out.File
	file_api_proto_notify_proto_goTypes = nil
	file_api_proto_notify_proto_depIdxs = nil
}
